//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSPDevTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpSkill
    {
        public int ID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> SkillD { get; set; }
        public Nullable<int> SkillLevelID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Skill_Level Skill_Levels { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
