//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSPDevTool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSPEntities : DbContext
    {
        public TSPEntities()
            : base("name=TSPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmpSkill> EmpSkills { get; set; }
        public virtual DbSet<EmpSubsidary> EmpSubsidaries { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Skill_Level> Skill_Levels { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Subsidary> Subsidaries { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
        public virtual DbSet<TrackSkill> TrackSkills { get; set; }
        public virtual DbSet<Workload> Workloads { get; set; }
    }
}
