//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSPDevTools.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackSkill
    {
        public int ID { get; set; }
        public int SkillD { get; set; }
        public int TrackID { get; set; }
    
        public virtual Skill Skill { get; set; }
        public virtual Track Track { get; set; }
    }
}
